version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - otp_network
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - otp_network
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - otp_network
    restart: unless-stopped

networks:
  otp_network:
    driver: bridge